apiVersion: v2
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.6.7
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.11.3
name: chatwoot
description: Open-source customer engagement suite, an alternative to Intercom, Zendesk, Salesforce Service Cloud etc. 🔥💬
type: application
keywords:
  - chatwoot
  - open source
  - customer support
  - chat
  - ruby
  - rails
  - crm
maintainers:
  - name: hamza nael
    email: hamza@ctech.company
home: https://github.com/Hamzanael/charts-telelogx
icon: https://chatwoot-public-assets.s3.amazonaws.com/logo/square.png
sources:
  - https://github.com/Hamzanael/chatwoot-telelogx
  - http://www.chatwoot.com

# This is the chart version.
version: 1.0.73

# This is the application version.
appVersion: "v1.0.27-ce-telelogx"
